### ISSUE TITLE
Regel lengte

### ISSUE THREAD

**Issue by MokhtarAkle** [amirdev98/connect-your-tribe-squad-page#8]
Kijk goed naar de regellengte principes besproken in het meegeleverde artikel. Probeer een ideale regellengte in te stellen en hou deze responsive aan.

Artikel: https://learn.bakermen.com/8-onmisbare-tips-voor-typografie-in-webdesign

**Comment by amirnapoletano** [comment]
Dankjewel Mokhtar, zal ik doen)
